output "workspace_region" {
  description = "AWS region effectively used by this workspace. Surfaced so downstream tooling (CI evidence scripts, runbooks) doesn't have to re-derive it from var.region."
  value       = var.region
}

# --- Storage outputs ---------------------------------------------------------

output "attachments_bucket_name" {
  description = "Name of the S3 bucket holding ticket attachments (screenshots, logs, PDFs uploaded by users)."
  value       = module.attachments_bucket.bucket_name
}

output "attachments_bucket_arn" {
  description = "ARN of the attachments bucket. Consumed by IAM policies in later deliveries."
  value       = module.attachments_bucket.bucket_arn
}

output "reports_bucket_name" {
  description = "Name of the S3 bucket holding monthly PDF reports generated by the reporte-pdf Lambda."
  value       = module.reports_bucket.bucket_name
}

output "reports_bucket_arn" {
  description = "ARN of the reports bucket. Consumed by IAM policies in later deliveries."
  value       = module.reports_bucket.bucket_arn
}

# --- Database outputs --------------------------------------------------------

output "database_table_name" {
  description = "Name of the DynamoDB single-table. Injected into Lambdas via TABLE_NAME environment variable."
  value       = module.database.table_name
}

output "database_table_arn" {
  description = "ARN of the DynamoDB table. Useful for cross-account IAM references in Delivery 5."
  value       = module.database.table_arn
}

output "database_stream_arn" {
  description = "ARN of the DynamoDB stream. Will be consumed by an audit Lambda in Delivery 4."
  value       = module.database.stream_arn
}

# --- Compute outputs (consolidated for evidence) -----------------------------

output "lambda_function_names" {
  description = "Map of logical lambda key -> function name. Used by the evidence script (aws lambda get-function) and by anyone wiring SQS/EventBridge triggers later."
  value = {
    api_tickets     = module.lambda_api_tickets.function_name
    webhook_ingesta = module.lambda_webhook_ingesta.function_name
    escalamiento    = module.lambda_escalamiento.function_name
    notificacion    = module.lambda_notificacion.function_name
    reporte_pdf     = module.lambda_reporte_pdf.function_name
  }
}

output "lambda_function_arns" {
  description = "Map of logical lambda key -> function ARN."
  value = {
    api_tickets     = module.lambda_api_tickets.function_arn
    webhook_ingesta = module.lambda_webhook_ingesta.function_arn
    escalamiento    = module.lambda_escalamiento.function_arn
    notificacion    = module.lambda_notificacion.function_arn
    reporte_pdf     = module.lambda_reporte_pdf.function_arn
  }
}

# --- Ingress (API Gateway) outputs -------------------------------------------

output "api_gateway_endpoint" {
  description = "Public HTTPS endpoint for the API Gateway HTTP API. Routes: incidents CRUD + state machine, comments, reassignment, POST /api/v1/webhooks/alerts, POST /api/v1/reports, health check."
  value       = module.ingress.api_endpoint
}

output "api_gateway_id" {
  description = "ID of the API Gateway HTTP API resource. Useful for CLI introspection in evidence steps."
  value       = module.ingress.api_id
}

output "ingress_url" {
  description = "Public ingress URL of the /api/v1/incidents resource — the E2E GET/POST endpoint exercised in Delivery 3."
  value       = module.ingress.incidents_url
}

output "health_check_url" {
  description = "Public health/readiness check URL exposed by the ingress."
  value       = module.ingress.health_check_url
}

# --- Async messaging outputs (Delivery 4) ------------------------------------

output "events_queue_url" {
  description = "URL of the main SQS events queue. Injected into the producer Lambda as QUEUE_URL and used by the seed enqueue in the E2E proof."
  value       = module.events_queue.queue_url
}

output "events_queue_arn" {
  description = "ARN of the main SQS events queue. Scopes the producer/consumer IAM statements and is the event_source_arn of the event source mapping."
  value       = module.events_queue.queue_arn
}

output "events_dlq_url" {
  description = "URL of the dead-letter queue. Inspect ApproximateNumberOfMessages here to see poison messages that exhausted max_receive_count."
  value       = module.events_queue.dlq_url
}

output "events_dlq_arn" {
  description = "ARN of the dead-letter queue."
  value       = module.events_queue.dlq_arn
}

output "event_source_mapping_uuid" {
  description = "UUID of the SQS -> notificacion event source mapping. Confirms the consumer is wired to the queue."
  value       = aws_lambda_event_source_mapping.events_to_notificacion.uuid
}

output "enqueue_url" {
  description = "Public producer endpoint (POST /api/v1/incidents/enqueue) reachable only through the D3 ingress."
  value       = module.ingress.enqueue_url
}

# --- Scheduled job outputs (Delivery 4) --------------------------------------

output "sla_sweep_schedule_name" {
  description = "Name of the EventBridge Scheduler schedule that invokes the escalamiento Lambda."
  value       = module.sla_sweep_scheduler.schedule_name
}

output "sla_sweep_schedule_arn" {
  description = "ARN of the EventBridge Scheduler schedule."
  value       = module.sla_sweep_scheduler.schedule_arn
}

# --- Network outputs ---------------------------------------------------------

output "vpc_id" {
  description = "ID of the project VPC provisioned by the network module."
  value       = module.network.vpc_id
}

output "public_subnet_ids" {
  description = "Public subnet IDs (one per AZ)."
  value       = module.network.public_subnet_ids
}

output "private_subnet_ids" {
  description = "All private subnet IDs (app + data)."
  value       = module.network.private_subnet_ids
}

output "private_app_subnet_ids" {
  description = "Private application subnet IDs (one per AZ)."
  value       = module.network.private_app_subnet_ids
}

output "private_data_subnet_ids" {
  description = "Private data subnet IDs (one per AZ, reserved)."
  value       = module.network.private_data_subnet_ids
}

output "nat_gateway_ids" {
  description = "NAT Gateway IDs (empty if NAT is disabled)."
  value       = module.network.nat_gateway_ids
}

# --- Security outputs --------------------------------------------------------

output "security_group_ids" {
  description = "Map of tier -> security group id (web/app/db)."
  value = {
    web = module.security.web_sg_id
    app = module.security.app_sg_id
    db  = module.security.db_sg_id
  }
}

# --- Delivery 5: KMS + Secrets (Deliverable B) -------------------------------

output "kms_key_arn" {
  description = "ARN of the customer-managed CMK encrypting S3, DynamoDB and the secret."
  value       = module.security_kms.kms_key_arn
}

output "kms_alias_name" {
  description = "Alias of the project CMK (alias/<name>)."
  value       = module.security_kms.kms_alias_name
}

output "secret_arn" {
  description = "ARN of the Secrets Manager DB-password secret (the value is never output)."
  value       = module.security_kms.secret_arn
}

output "secret_name" {
  description = "Name of the Secrets Manager DB-password secret."
  value       = module.security_kms.secret_name
}

# --- Delivery 5: IAM + OIDC (Deliverables A, C) ------------------------------

output "ci_runner_role_arn" {
  description = "ARN of the OIDC-assumable CI runner role (provisioned in the bootstrap workspace). Referenced by the GitHub Actions workflows' role-to-assume input."
  value       = local.ci_runner_role_arn
}

output "oidc_provider_arn" {
  description = "ARN of the GitHub Actions OIDC provider (provisioned in the bootstrap workspace)."
  value       = "arn:aws:iam::${local.account_id}:oidc-provider/token.actions.githubusercontent.com"
}

output "lambda_execution_role_arns" {
  description = "Map of service -> execution role ARN, proving each Lambda consumes a role from the central IAM module (none hardcoded)."
  value = {
    compute_api          = module.iam.compute_api_role_arn
    compute_webhook      = module.iam.compute_webhook_role_arn
    compute_escalamiento = module.iam.compute_escalamiento_role_arn
    async_consumer       = module.iam.async_consumer_role_arn
    compute_reporte      = module.iam.compute_reporte_role_arn
    scheduler            = module.iam.scheduler_role_arn
  }
}

# --- Delivery 5: TLS (Deliverable D) -----------------------------------------

output "tls_certificate_arn" {
  description = "ARN of the validated ACM certificate covering the API Gateway custom domain and the CloudFront endpoint (null when enable_tls = false)."
  value       = one(module.tls[*].certificate_arn)
}

output "api_custom_domain_url" {
  description = "Public HTTPS URL served by the API Gateway custom domain (regional cert). HTTPS only. null when enable_tls = false."
  value       = one(module.tls[*].api_url)
}

output "app_cloudfront_url" {
  description = "Public HTTPS URL served by CloudFront (the React SPA). Also issues an HTTP 301 redirect to HTTPS on port 80. null when enable_tls = false."
  value       = one(module.tls[*].app_url)
}

output "spa_bucket_name" {
  description = "Private S3 bucket the built SPA is uploaded to (deploy target). null when enable_tls = false."
  value       = one(module.tls[*].spa_bucket_name)
}

output "spa_cloudfront_distribution_id" {
  description = "CloudFront distribution ID for the SPA — used to invalidate the cache after a deploy. null when enable_tls = false."
  value       = one(module.tls[*].cloudfront_distribution_id)
}

output "public_endpoints" {
  description = "Every public-facing URL the application exposes, for the TLS coverage proof in delivery-5-summary.md."
  value = var.enable_tls ? {
    api_gateway_custom_domain = one(module.tls[*].api_url)
    cloudfront                = one(module.tls[*].app_url)
  } : {}
}

output "canonical_api_url" {
  description = "The HTTPS base URL clients (and the SPA's VITE_API_BASE) should use: the TLS custom domain when enable_tls = true, otherwise the API Gateway execute-api endpoint. Both are HTTPS."
  value       = var.enable_tls ? one(module.tls[*].api_url) : module.ingress.api_endpoint
}

# --- Application notifications (US-05/US-06) ---------------------------------

output "notifications_topic_arn" {
  description = "ARN of the SNS topic the notificacion worker publishes ticket events to (escalations, resolutions, report-ready links)."
  value       = aws_sns_topic.notifications.arn
}

# --- Delivery 5: Observability (Deliverable E) -------------------------------

output "observability_log_group_arns" {
  description = "Map of service -> CloudWatch log group ARN. Captured for infra/evidence/observability-outputs.txt."
  value       = module.observability.log_group_arns
}

output "observability_alarm_arns" {
  description = "ARNs of every CloudWatch alarm. Captured for infra/evidence/observability-outputs.txt."
  value       = module.observability.alarm_arns
}

output "observability_sns_topic_arn" {
  description = "ARN of the SNS topic delivering alarm and budget notifications by email."
  value       = module.observability.sns_topic_arn
}

output "observability_dashboard_name" {
  description = "Name of the CloudWatch dashboard."
  value       = module.observability.dashboard_name
}

output "observability_budget_name" {
  description = "Name of the monthly cost budget."
  value       = module.observability.budget_name
}
