output "workspace_region" {
  description = "AWS region effectively used by this workspace. Surfaced so downstream tooling (CI evidence scripts, runbooks) doesn't have to re-derive it from var.region."
  value       = var.region
}

# --- Storage outputs ---------------------------------------------------------

output "attachments_bucket_name" {
  description = "Name of the S3 bucket holding ticket attachments (screenshots, logs, PDFs uploaded by users)."
  value       = module.attachments_bucket.bucket_name
}

output "attachments_bucket_arn" {
  description = "ARN of the attachments bucket. Consumed by IAM policies in later deliveries."
  value       = module.attachments_bucket.bucket_arn
}

output "reports_bucket_name" {
  description = "Name of the S3 bucket holding monthly PDF reports generated by the reporte-pdf Lambda."
  value       = module.reports_bucket.bucket_name
}

output "reports_bucket_arn" {
  description = "ARN of the reports bucket. Consumed by IAM policies in later deliveries."
  value       = module.reports_bucket.bucket_arn
}

# --- Database outputs --------------------------------------------------------

output "database_table_name" {
  description = "Name of the DynamoDB single-table. Injected into Lambdas via TABLE_NAME environment variable."
  value       = module.database.table_name
}

output "database_table_arn" {
  description = "ARN of the DynamoDB table. Useful for cross-account IAM references in Delivery 5."
  value       = module.database.table_arn
}

output "database_stream_arn" {
  description = "ARN of the DynamoDB stream. Will be consumed by an audit Lambda in Delivery 4."
  value       = module.database.stream_arn
}

# --- Compute outputs (consolidated for evidence) -----------------------------

output "lambda_function_names" {
  description = "Map of logical lambda key -> function name. Used by the evidence script (aws lambda get-function) and by anyone wiring SQS/EventBridge triggers later."
  value = {
    api_tickets     = module.lambda_api_tickets.function_name
    webhook_ingesta = module.lambda_webhook_ingesta.function_name
    escalamiento    = module.lambda_escalamiento.function_name
    notificacion    = module.lambda_notificacion.function_name
    reporte_pdf     = module.lambda_reporte_pdf.function_name
  }
}

output "lambda_function_arns" {
  description = "Map of logical lambda key -> function ARN."
  value = {
    api_tickets     = module.lambda_api_tickets.function_arn
    webhook_ingesta = module.lambda_webhook_ingesta.function_arn
    escalamiento    = module.lambda_escalamiento.function_arn
    notificacion    = module.lambda_notificacion.function_arn
    reporte_pdf     = module.lambda_reporte_pdf.function_arn
  }
}

# --- API Gateway outputs -----------------------------------------------------

output "api_gateway_endpoint" {
  description = "Public HTTPS endpoint for the API Gateway HTTP API. Routes: POST /api/v1/incidents, POST /api/v1/webhooks."
  value       = aws_apigatewayv2_api.main.api_endpoint
}

output "api_gateway_id" {
  description = "ID of the API Gateway HTTP API resource. Useful for CLI introspection in evidence steps."
  value       = aws_apigatewayv2_api.main.id
}
