output "workspace_region" {
  description = "AWS region effectively used by this workspace. Surfaced so downstream tooling (CI evidence scripts, runbooks) doesn't have to re-derive it from var.region."
  value       = var.region
}

# --- Storage outputs ---------------------------------------------------------

output "attachments_bucket_name" {
  description = "Name of the S3 bucket holding ticket attachments (screenshots, logs, PDFs uploaded by users)."
  value       = module.attachments_bucket.bucket_name
}

output "attachments_bucket_arn" {
  description = "ARN of the attachments bucket. Consumed by IAM policies in later deliveries."
  value       = module.attachments_bucket.bucket_arn
}

output "reports_bucket_name" {
  description = "Name of the S3 bucket holding monthly PDF reports generated by the reporte-pdf Lambda."
  value       = module.reports_bucket.bucket_name
}

output "reports_bucket_arn" {
  description = "ARN of the reports bucket. Consumed by IAM policies in later deliveries."
  value       = module.reports_bucket.bucket_arn
}

# --- Database outputs --------------------------------------------------------

output "database_table_name" {
  description = "Name of the DynamoDB single-table. Injected into Lambdas via TABLE_NAME environment variable."
  value       = module.database.table_name
}

output "database_table_arn" {
  description = "ARN of the DynamoDB table. Useful for cross-account IAM references in Delivery 5."
  value       = module.database.table_arn
}

output "database_stream_arn" {
  description = "ARN of the DynamoDB stream. Will be consumed by an audit Lambda in Delivery 4."
  value       = module.database.stream_arn
}

# --- Compute outputs (consolidated for evidence) -----------------------------

output "lambda_function_names" {
  description = "Map of logical lambda key -> function name. Used by the evidence script (aws lambda get-function) and by anyone wiring SQS/EventBridge triggers later."
  value = {
    api_tickets     = module.lambda_api_tickets.function_name
    webhook_ingesta = module.lambda_webhook_ingesta.function_name
    escalamiento    = module.lambda_escalamiento.function_name
    notificacion    = module.lambda_notificacion.function_name
    reporte_pdf     = module.lambda_reporte_pdf.function_name
  }
}

output "lambda_function_arns" {
  description = "Map of logical lambda key -> function ARN."
  value = {
    api_tickets     = module.lambda_api_tickets.function_arn
    webhook_ingesta = module.lambda_webhook_ingesta.function_arn
    escalamiento    = module.lambda_escalamiento.function_arn
    notificacion    = module.lambda_notificacion.function_arn
    reporte_pdf     = module.lambda_reporte_pdf.function_arn
  }
}

# --- Ingress (API Gateway) outputs -------------------------------------------

output "api_gateway_endpoint" {
  description = "Public HTTPS endpoint for the API Gateway HTTP API. Routes: GET/POST /api/v1/incidents, POST /api/v1/webhooks, GET health check."
  value       = module.ingress.api_endpoint
}

output "api_gateway_id" {
  description = "ID of the API Gateway HTTP API resource. Useful for CLI introspection in evidence steps."
  value       = module.ingress.api_id
}

output "ingress_url" {
  description = "Public ingress URL of the /api/v1/incidents resource — the E2E GET/POST endpoint exercised in Delivery 3."
  value       = module.ingress.incidents_url
}

output "health_check_url" {
  description = "Public health/readiness check URL exposed by the ingress."
  value       = module.ingress.health_check_url
}

# --- Async messaging outputs (Delivery 4) ------------------------------------

output "events_queue_url" {
  description = "URL of the main SQS events queue. Injected into the producer Lambda as QUEUE_URL and used by the seed enqueue in the E2E proof."
  value       = module.events_queue.queue_url
}

output "events_queue_arn" {
  description = "ARN of the main SQS events queue. Scopes the producer/consumer IAM statements and is the event_source_arn of the event source mapping."
  value       = module.events_queue.queue_arn
}

output "events_dlq_url" {
  description = "URL of the dead-letter queue. Inspect ApproximateNumberOfMessages here to see poison messages that exhausted max_receive_count."
  value       = module.events_queue.dlq_url
}

output "events_dlq_arn" {
  description = "ARN of the dead-letter queue."
  value       = module.events_queue.dlq_arn
}

output "event_source_mapping_uuid" {
  description = "UUID of the SQS -> notificacion event source mapping. Confirms the consumer is wired to the queue."
  value       = aws_lambda_event_source_mapping.events_to_notificacion.uuid
}

output "enqueue_url" {
  description = "Public producer endpoint (POST /api/v1/incidents/enqueue) reachable only through the D3 ingress."
  value       = module.ingress.enqueue_url
}

# --- Scheduled job outputs (Delivery 4) --------------------------------------

output "sla_sweep_schedule_name" {
  description = "Name of the EventBridge Scheduler schedule that invokes the escalamiento Lambda."
  value       = module.sla_sweep_scheduler.schedule_name
}

output "sla_sweep_schedule_arn" {
  description = "ARN of the EventBridge Scheduler schedule."
  value       = module.sla_sweep_scheduler.schedule_arn
}

# --- Network outputs ---------------------------------------------------------

output "vpc_id" {
  description = "ID of the project VPC provisioned by the network module."
  value       = module.network.vpc_id
}

output "public_subnet_ids" {
  description = "Public subnet IDs (one per AZ)."
  value       = module.network.public_subnet_ids
}

output "private_subnet_ids" {
  description = "All private subnet IDs (app + data)."
  value       = module.network.private_subnet_ids
}

output "private_app_subnet_ids" {
  description = "Private application subnet IDs (one per AZ)."
  value       = module.network.private_app_subnet_ids
}

output "private_data_subnet_ids" {
  description = "Private data subnet IDs (one per AZ, reserved)."
  value       = module.network.private_data_subnet_ids
}

output "nat_gateway_ids" {
  description = "NAT Gateway IDs (empty if NAT is disabled)."
  value       = module.network.nat_gateway_ids
}

# --- Security outputs --------------------------------------------------------

output "security_group_ids" {
  description = "Map of tier -> security group id (web/app/db)."
  value = {
    web = module.security.web_sg_id
    app = module.security.app_sg_id
    db  = module.security.db_sg_id
  }
}
